[package]
name = "vrsc-rpc"
description = "A wrapper for Verus RPCs"
version = "0.0.2"
authors = ["jorian"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrsc-rpc-json = { version = "0.0.2", path = "../json" }

jsonrpc = "0.12"
os_info = "3.0"
dirs = "4.0"
serde = "1.0.115"
serde_json = "1.0.57"
tracing = "0.1.26"
