[package]
name = "vrsc-rpc-json"
description = ""
version = "0.0.1"
authors = ["jorian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
hex = "0.3"

bitcoin = { version = "0.26.2", features = [ "use-serde" ] }
# vrsc = { version = "0.1.0", git = "ssh://github.com/jorian/rust-vrsc" }
vrsc = { version = "0.1.0", path = "../../rust-vrsc" }